services:
  # Backend service
  - type: web
    name: pawfect-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && gunicorn app:app --bind 0.0.0.0:$PORT --workers 4
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 10000
    healthCheckPath: /
    autoDeploy: true

  # Frontend service
  - type: web
    name: pawfect-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run preview -- --host 0.0.0.0 --port $PORT
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
      - key: PORT
        value: 10000
    healthCheckPath: /
    autoDeploy: true
    # Add your frontend environment variables here
    # - key: VITE_API_URL
    #   value: https://pawfect-backend.onrender.com 